# Generated by Django 5.0.2 on 2024-02-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginmodels',
            old_name='b',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='loginmodels',
            old_name='a',
            new_name='username',
        ),
    ]
